name: Compose Screenshot Test

permissions:
  packages: read

on:
  pull_request:
    paths:
      - 'androidApp/src/main/**/*.kt'
      - 'androidApp/src/main/**/*.xml'
      - 'shared/src/commonMain/**/*.kt'
      - 'shared/src/androidMain/**/*.kt'
      - 'androidApp/src/screenshotTest/**'

jobs:
  screenshot-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Validate Compose Screenshots
        run: ./gradlew :androidApp:validateDebugScreenshotTest
        env:
          ORG_GRADLE_PROJECT_gpr_user: ${{ github.actor }}
          ORG_GRADLE_PROJECT_gpr_key: ${{ secrets.GPR_TOKEN }}

      - name: Upload Screenshot Test Report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshot-test-report
          path: androidApp/build/reports/screenshotTest/
